"""Savings Goals API endpoints."""

from typing import Optional, Dict, Any


class SavingsGoalsAPI:
    """API for savings goal-related operations."""

    def __init__(self, client):
        """Initialize with a StarlingClient instance."""
        self.client = client

    def get_savings_goals(self, account_uid: str) -> Dict[str, Any]:
        """
        Get all savings goals.

        Args:
            account_uid: Account UID

        Requires: savings-goal:read OAuth scope

        Returns:
            SavingsGoalsV2 object
        """
        return self.client.get(f"/api/v2/account/{account_uid}/savings-goals")

    def get_savings_goal(self, account_uid: str, savings_goal_uid: str) -> Dict[str, Any]:
        """
        Get a savings goal.

        Args:
            account_uid: Account UID
            savings_goal_uid: Savings goal UID

        Requires: savings-goal:read OAuth scope

        Returns:
            SavingsGoalV2 object
        """
        return self.client.get(f"/api/v2/account/{account_uid}/savings-goals/{savings_goal_uid}")

    def create_savings_goal(
        self,
        account_uid: str,
        name: str,
        currency: str,
        target: Optional[Dict[str, Any]] = None,
        base64_encoded_photo: Optional[str] = None,
    ) -> Dict[str, Any]:
        """
        Create a savings goal.

        Args:
            account_uid: Account UID
            name: Name of the savings goal
            currency: ISO-4217 3 character currency code
            target: CurrencyAndAmount object for target (optional)
            base64_encoded_photo: Base64 encoded picture (optional)

        Requires: savings-goal:create OAuth scope

        Returns:
            CreateOrUpdateSavingsGoalResponseV2 object
        """
        json_data = {"name": name, "currency": currency}

        if target:
            json_data["target"] = target
        if base64_encoded_photo:
            json_data["base64EncodedPhoto"] = base64_encoded_photo

        return self.client.put(f"/api/v2/account/{account_uid}/savings-goals", json_data=json_data)

    def update_savings_goal(
        self,
        account_uid: str,
        savings_goal_uid: str,
        name: str,
        currency: str,
        target: Optional[Dict[str, Any]] = None,
        base64_encoded_photo: Optional[str] = None,
    ) -> Dict[str, Any]:
        """
        Update an existing savings goal.

        Args:
            account_uid: Account UID
            savings_goal_uid: Savings goal UID
            name: Name of the savings goal
            currency: ISO-4217 3 character currency code
            target: CurrencyAndAmount object for target (optional)
            base64_encoded_photo: Base64 encoded picture (optional)

        Requires: savings-goal:create OAuth scope

        Returns:
            CreateOrUpdateSavingsGoalResponseV2 object
        """
        json_data = {"name": name, "currency": currency}

        if target:
            json_data["target"] = target
        if base64_encoded_photo:
            json_data["base64EncodedPhoto"] = base64_encoded_photo

        return self.client.put(
            f"/api/v2/account/{account_uid}/savings-goals/{savings_goal_uid}", json_data=json_data
        )

    def delete_savings_goal(self, account_uid: str, savings_goal_uid: str) -> Dict[str, Any]:
        """
        Delete a savings goal.

        Args:
            account_uid: Account UID
            savings_goal_uid: Savings goal UID

        Requires: savings-goal:delete OAuth scope

        Returns:
            Empty dict on success
        """
        return self.client.delete(
            f"/api/v2/account/{account_uid}/savings-goals/{savings_goal_uid}"
        )

    def get_savings_goal_photo(self, account_uid: str, savings_goal_uid: str) -> Dict[str, Any]:
        """
        Get the photo associated with a savings goal.

        Args:
            account_uid: Account UID
            savings_goal_uid: Savings goal UID

        Requires: savings-goal:read OAuth scope

        Returns:
            SavingsGoalPhotoV2 object
        """
        return self.client.get(
            f"/api/v2/account/{account_uid}/savings-goals/{savings_goal_uid}/photo"
        )

    def add_money(
        self,
        account_uid: str,
        savings_goal_uid: str,
        transfer_uid: str,
        amount: Dict[str, Any],
        reference: Optional[str] = None,
    ) -> Dict[str, Any]:
        """
        Add money into a savings goal.

        Args:
            account_uid: Account UID
            savings_goal_uid: Savings goal UID
            transfer_uid: Transfer UID (generated by caller, use uuid.uuid4())
            amount: CurrencyAndAmount object
            reference: Reference for the transfer (optional)

        Requires: savings-goal-transfer:create OAuth scope

        Returns:
            SavingsGoalTransferResponseV2 object
        """
        json_data = {"amount": amount}
        if reference:
            json_data["reference"] = reference

        return self.client.put(
            f"/api/v2/account/{account_uid}/savings-goals/{savings_goal_uid}/add-money/{transfer_uid}",
            json_data=json_data,
        )

    def withdraw_money(
        self,
        account_uid: str,
        savings_goal_uid: str,
        transfer_uid: str,
        amount: Dict[str, Any],
        reference: Optional[str] = None,
    ) -> Dict[str, Any]:
        """
        Withdraw money from a savings goal.

        Args:
            account_uid: Account UID
            savings_goal_uid: Savings goal UID
            transfer_uid: Transfer UID (generated by caller, use uuid.uuid4())
            amount: CurrencyAndAmount object
            reference: Reference for the withdrawal (optional)

        Requires: savings-goal-transfer:create OAuth scope

        Returns:
            SavingsGoalTransferResponseV2 object
        """
        json_data = {"amount": amount}
        if reference:
            json_data["reference"] = reference

        return self.client.put(
            f"/api/v2/account/{account_uid}/savings-goals/{savings_goal_uid}/withdraw-money/{transfer_uid}",
            json_data=json_data,
        )

    def get_recurring_transfer(
        self, account_uid: str, savings_goal_uid: str
    ) -> Dict[str, Any]:
        """
        Get the recurring transfer of a savings goal.

        Args:
            account_uid: Account UID
            savings_goal_uid: Savings goal UID

        Requires: savings-goal-transfer:read OAuth scope

        Returns:
            ScheduledSavingsPaymentV2 object
        """
        return self.client.get(
            f"/api/v2/account/{account_uid}/savings-goals/{savings_goal_uid}/recurring-transfer"
        )

    def create_recurring_transfer(
        self,
        account_uid: str,
        savings_goal_uid: str,
        recurrence_rule: Dict[str, Any],
        amount: Dict[str, Any],
        top_up: bool = False,
        reference: Optional[str] = None,
    ) -> Dict[str, Any]:
        """
        Create a recurring transfer into a savings goal.

        Args:
            account_uid: Account UID
            savings_goal_uid: Savings goal UID
            recurrence_rule: RecurrenceRuleV2 object
            amount: CurrencyAndAmount object
            top_up: If the payment is a top up or not
            reference: Reference used on each occasion (optional)

        Requires: savings-goal-transfer:create OAuth scope

        Returns:
            SavingsGoalTransferResponseV2 object
        """
        json_data = {
            "recurrenceRule": recurrence_rule,
            "amount": amount,
            "topUp": top_up,
        }

        if reference:
            json_data["reference"] = reference

        return self.client.put(
            f"/api/v2/account/{account_uid}/savings-goals/{savings_goal_uid}/recurring-transfer",
            json_data=json_data,
        )

    def delete_recurring_transfer(
        self, account_uid: str, savings_goal_uid: str
    ) -> Dict[str, Any]:
        """
        Delete the recurring transfer of a savings goal.

        Args:
            account_uid: Account UID
            savings_goal_uid: Savings goal UID

        Requires: savings-goal-transfer:delete OAuth scope

        Returns:
            Empty dict on success
        """
        return self.client.delete(
            f"/api/v2/account/{account_uid}/savings-goals/{savings_goal_uid}/recurring-transfer"
        )